[WIP] Getting Started Tooltip
ecency/ecency-mobile pull request #2164
Opened 2022-01-28 14:10 UTC by aliseyalvi

### What does this PR?

- Updated react-native-modal-popover module
- Created Tooltip component using react-native-modal-popover
- Added Tooltip in Editor Screen on Draft button
Work is in progress. Need further enhancements and modifications

### Issue number
Trello: Improve: Add new install draft button tooltip in editor screen

### Screenshots/Video
https://www.loom.com/share/49e55b781f924b4fa546a691e853c6ce

2022-02-02 17:24 UTC, aliseyalvi commented
@noumantahir registered tooltip in redux when it loads for first time. Checkout the latest update  https://github.com/ecency/ecency-mobile/pull/2164/commits/3f2b0d968d0dcf23e1468799098ac2836e8c1b51
https://www.loom.com/share/d32a4965dba641b0b377f7506e22c558

2022-02-08 07:18 UTC, feruzm commented on src/components/markdownEditor/view/markdownEditorView.js
> +            <Tooltip ref={tooltipRef} text="This is Draft" walkthroughId="DRAFT_BTN_TOOLTIP">
String should be in Translation files

2022-02-08 10:50 UTC, noumantahir requested changes
The requested changes are tweaked towards making the structure scaleable as we move forward. Though tight now we only have tooltip for drafts but we should still structure it so we face minimal roadblocks as we scale

2022-02-08 15:57 UTC, aliseyalvi commented
@noumantahir updated redux store according to your review. Storing walkthrough indices inside map and keys in constants file. Registering a tooltip is a bit different process. Actually controlling this process from ref object so that parent has access to the method. 
Latest commit https://github.com/ecency/ecency-mobile/pull/2164/commits/f408db9979de0d53102401d998c4fdfe0479a1d9

2022-02-09 06:32 UTC, noumantahir requested changes
I reviewed the code changed, I am glad we are moving the right direction, just a few more changes and we should be good.

However, functionality wise I was unable to test the app as it crashed as soon I entered the editor screen, apparently we need a null check for walkthrough map but cannot say for sure.. What I can say is redux crashes in this way when an older version of reducer is already present in existing app.

![Screenshot 2022-02-09 at 11 22 01 AM](https://user-images.githubusercontent.com/6298342/153134621-62447436-4036-4e8f-8af5-34cd76eb6a62.png)


Update: tried a new install, app still crashed but with a different error this time....

![Screenshot 2022-02-09 at 11 34 34 AM](https://user-images.githubusercontent.com/6298342/153135200-a448c245-6c24-49f2-97d6-7c7771e6c1f9.png)

2022-02-09 06:32 UTC, noumantahir commented on src/redux/reducers/index.js
> +  tooltips: tooltipsReducer,
@aliseyalvi  perhaps renaming `tooltipsReducer` / actions to `walkthroughReducer`/action will make more self elaborative, what do you think?

2022-02-09 06:32 UTC, noumantahir commented on src/redux/reducers/tooltipsReducer.ts
> +export interface Walkthrough {
suggestion: perhaps should be renamed to `WalkthroughItem` ?

2022-02-09 06:32 UTC, noumantahir commented on src/config/locales/en-US.json
> +    "load_draft_tooltip": "Load your lastest draft here"
Let's introduce a separate section where all walkthrough related texts reside so it's easier to manage them in one place later...? moving forward we can even devise some mechanism to pair them with walkthrough ids, but not now.

```
"walkthrough":{
   "load_draft":"asdfasldkf"
}
```

2022-02-09 08:41 UTC, aliseyalvi commented
@noumantahir added tarnsform function for walkthroughRedcuer and renamed reducer and actions. Used map in reducer and I think it is flexible enough to implement the walkhrough for the app.
Check latest update here https://github.com/ecency/ecency-mobile/pull/2164/commits/bdfa973e90c5171ef8d6fe6b6957a36bb7752527

2022-02-09 09:09 UTC, noumantahir approved these changes
lgtm

2022-02-09 09:10 UTC, merged