[WIP] Redesign Power Down Screen
ecency/ecency-mobile pull request #2269
Opened 2022-04-19 05:28 UTC by aliseyalvi

### What does this PR?
This PR redesigns powerdown screen similar to delegate screen. 

- Reused beneficiary selection module from post options modal. Currently it is placed separately in components and beneficiary in post options modal isn't replaced with this one but can be replaced later.
- redesigned slider and value input similar to delegate screen.

### Todos

- text has to be replaced with suitable text and titles
- multi step has to be done, 
- currently OptionsModal has been used for confirmation, may be need to be replaced with more intuitive actions sheet with some extra info of the operation.
- code cleanup is also remaining as for now commented the old code, maybe we need to reuse some info from there as well like info related to incoming funds , still needs to decide place for incoming funds and then we can place them accordingly.
- 

### Issue number
fixes #2246 

### Screenshots/Video

https://user-images.githubusercontent.com/48380998/163926249-6c2bfa81-7131-441e-a675-8f3a2f3c37c5.mp4

2022-04-19 12:15 UTC, noumantahir commented on src/components/beneficiarySelectionContent/beneficiarySelectionContent.tsx
> +  const beneficiariesMap = useAppSelector((state) => state.editor.beneficiariesMap);
Map should be fed as prop instead of state from redux, because it is fetching same beneficiaries in power down screen which should not be the case.

2022-04-19 12:23 UTC, noumantahir requested changes
I have not reviewed code in detail yet but beneficiary content can be generalised rather than having different reading mechanism for power down and beneficiary.

 functionality wise it is working well... check the screenshot below for changes required

Auto Vests label can be multiline perhaps

<img width="282" alt="Screenshot 2022-04-19 at 5 19 57 PM 1" src="https://user-images.githubusercontent.com/6298342/164002430-29121912-fdca-4142-8b54-f2f3defce51c.png">

2022-04-19 13:15 UTC, aliseyalvi commented
> I have not reviewed code in detail yet but beneficiary content can be generalised rather than having different reading mechanism for power down and beneficiary.
> 
> functionality wise it is working well... check the screenshot below for changes required
> 
> Auto Vests label can be multiline perhaps
> 
> <img alt="Screenshot 2022-04-19 at 5 19 57 PM 1" width="282" src="https://user-images.githubusercontent.com/6298342/164002430-29121912-fdca-4142-8b54-f2f3defce51c.png">

yeah that can be generalised, the reason I didn't replaced the beneficiary selection module in post options modal with this one is that we can do that in separate PR after this one is done, I am just cautious and dont want to break things

2022-04-20 23:38 UTC, noumantahir approved these changes

2022-04-20 23:39 UTC, noumantahir commented
Fine tuned power down screen UI...
<img width="348" alt="Screenshot 2022-04-21 at 4 37 48 AM" src="https://user-images.githubusercontent.com/6298342/164341791-40aec392-dffe-43b0-921b-3b97d197ec19.png">

2022-04-21 04:04 UTC, feruzm approved these changes
Lgtm

2022-04-21 04:04 UTC, merged