show login fail alert
ecency/ecency-mobile pull request #2446
Opened 2022-09-05 17:03 UTC by aliseyalvi

### What does this PR?
Show login fail alert if login is failed or any error occured while logging in

### Issue number
fixes #2397 

### Screenshots/Video
![image](https://user-images.githubusercontent.com/48380998/188492865-1bfeab5c-1f29-4a24-b915-85109514a33e.png)

2022-09-06 09:14 UTC, noumantahir requested changes
@aliseyalvi please refer to responses reference shared by feruz here... https://discord.com/channels/@me/920267778190086205/1015152720023388232

For instance, in screenshot below there is a description of error provided that are simply discarding which is wrong imo
![Screenshot 2022-09-06 at 2 10 13 PM](https://user-images.githubusercontent.com/6298342/188596081-487880ff-0370-4014-bb99-87e37a644208.png)

If there is not error_description returned, then you may use the default error message login_failed_body. or perhaps we can add a second line asking user to try different key/password

2022-09-08 18:43 UTC, aliseyalvi commented
@noumantahir Updated:
Updated alert based on response returned from api call and if there is no error description it will show default error message with default error body

Uploading screencast 2022-09-08 23-28-07.mp4…

2022-09-09 19:42 UTC, noumantahir approved these changes
this should do it....

2022-09-09 19:54 UTC, feruzm approved these changes

2022-09-09 19:54 UTC, merged