Issue/publising platform
ecency/ecency-mobile pull request #2674
Opened 2023-04-19 11:44 UTC by SaadAli-rolustech

**What does this PR?**
This PR consists of the functionality from which app, the content was published for each post.

**Where should the reviewer start?**
File name: postDisplayView.tsx

### Steps to reproduce

**Issue number**
https://github.com/ecency/ecency-mobile/issues/2670

 **Screenshots/Video**
![Screenshot 2023-04-19 at 4 43 07 PM](https://user-images.githubusercontent.com/39906620/233064665-7554b2bc-e710-4193-9fab-01dffe7a6ae6.png)

2023-04-19 17:28 UTC, noumantahir requested changes
@SaadAli-rolustech  good effort overall, just a few simple things needs addressing....

2023-04-19 17:28 UTC, noumantahir commented on src/config/ecencyApi.ts
> +import Reactotron from 'reactotron-react-native';
We do no use `Reactotron` imports directly in production code, as production build strips reactotron-react-native package and cause app to crash if not in debug mode... there is a workaround to it by using `console.tron` but I have not configured it in this project yet. we usually use regular` console.log`, `console.debug` for now as it is configured to be removed before production.

2023-04-19 17:28 UTC, noumantahir commented on ios/Ecency.xcodeproj/project.pbxproj
try not to include both android and ios configs files in PR, unless some package exclusively updated or configuration is deliberately change. both of which does not seem to be a case here... usually config changes that slip to our CI/CD often messes with the production builds

2023-04-19 17:28 UTC, noumantahir commented on src/components/postView/view/postDisplayView.tsx
> +                  Published using{` ${capitalize((post?.json_metadata?.app).split('/')[0])} `}
updated presentation as suggested by Feruz here... https://discord.com/channels/@me/920267778190086205/1098233745959555112

2023-04-20 06:22 UTC, SaadAli-rolustech commented on ios/Ecency.xcodeproj/project.pbxproj
Noted.

2023-04-20 21:17 UTC, noumantahir requested changes
Just some small change requests. it might seem a little daunting getting yourself familiar with how we work, but ones you get accustom to the process it should smooth out and feel free to drop suggestions to improving and automating the process as well, always open to discuss and adapt.

2023-04-20 21:17 UTC, noumantahir commented on src/components/postView/view/postDisplayView.tsx
>                    Posted by
as suggested by feruz, use translations here... there is format supported by intl that supports injecting values in translation entries....

Code: `intl.formatMessage({id:'some_id'}, {username:'some_value_1', appName:'some_value_2'})`
en_US entry:` "some_id":"Posted by $usename via $appName"`

2023-04-20 21:17 UTC, noumantahir commented on src/utils/wallet.ts
> -
try not to include all lint results in PR, I do have plans to an app wide some time soon, the ts rules needs to be updated before we can properly do that... for now only hand pick linted files that you change in a particular PR. Another tip regarding lint.

I personally usually skip pre-commit hooks and lint manually before PR as some times lint can also break the app, not doing auto commit with lint gives me a chance to make sure lint did not break anything in app

2023-05-04 12:54 UTC, closed without merging