2671: Clone draft functionality with react query
ecency/ecency-mobile pull request #2677
Opened 2023-04-28 11:10 UTC by SaadAli-rolustech

**What does this PR?**
-clone button added on draft list item
- user can clone a draft

 **Issue number**
https://github.com/ecency/ecency-mobile/issues/2671

 **Screenshots/Video**

https://user-images.githubusercontent.com/39906620/235132628-1780b581-343d-4dc0-9f65-430fe242aef2.mov

2023-04-28 11:43 UTC, noumantahir requested changes
Great job on this PR @SaadAli-rolustech

As discussed in meeting, couple changes required.....

- [x] use filled copy instead of bordered or change both delete and copy to bordered icons
- [x] instead of creating clone mutation separate, make on addDraftMutation that we can used later in editorContainer as well.

2023-05-04 10:12 UTC, SaadAli-rolustech commented
Thank you for the feedback. The PR has been updated, Please review it.

2023-05-04 18:14 UTC, noumantahir requested changes
looking good, just a tinee tiny change for code cleaning....

2023-05-04 18:14 UTC, noumantahir commented on src/providers/ecency/ecency.ts
> +    if (action === 'add') {
using exclusive property `action` may be unnecessary and confusing for later use... why not just return the full response data array, `editorContainer` can just post process to extract last draft item....

2023-05-15 20:50 UTC, noumantahir requested changes
please test both cloning and saving new draft from editor screen

2023-05-15 20:50 UTC, noumantahir commented on src/providers/ecency/ecency.ts
> +    return res.data || [];
please test addDraft response again, it should return array of drafts... res.data do not contain the expected array....
https://media.discordapp.net/attachments/1094029149892509767/1103977166485598218/Screenshot_2023-05-05_at_2.30.31_PM.png

2023-05-22 14:05 UTC, noumantahir approved these changes
wrapped up PR, fixed addDraft response processing

2023-05-22 14:07 UTC, merged