[WIP] backup/import private keys
ecency/ecency-mobile pull request #2681
Opened 2023-05-04 19:02 UTC by aliseyalvi

### What does this PR?
This PR adds functionality of viewing/importing private/public keys stored in the app.
User can view/copy private or public keys and if user is logged in with active/posting/memo key he can import other keys by providing master key / password

### Issue number
fixes #2680 

### Screenshots/Video

2023-05-22 12:43 UTC, noumantahir requested changes
All seems to be good, require review from @feruzm, I added one comment as review regarding import keys when using hiveSigner, do check that .... 

other than that, one suggestion I may add, perhaps we should ask for pinCode if it's active before letting user access keys screen, it should be a simple step to integrate....
![Screenshot 2023-05-22 at 5 40 55 PM](https://github.com/ecency/ecency-mobile/assets/6298342/75ce6681-436e-47d3-8065-2e2c8e3971ef)
![Screenshot 2023-05-22 at 5 40 35 PM](https://github.com/ecency/ecency-mobile/assets/6298342/45be686d-b77b-4860-bd98-78624cde0b59)

2023-05-25 19:56 UTC, noumantahir requested changes
@aliseyalvi please carefully test your implementations, the pinCode integration you have done have several issues I have added in review comment, though I do understand this might be your first time working with pinCode screen......

2023-05-25 19:56 UTC, noumantahir commented on src/screens/settings/container/settingsContainer.tsx
> +        if (isPinCodeOpen) {
@aliseyalvi please redo this part, the current implementation will,

- make users not using pinCode unable to access manage screen
- break functionality for those already using pinCode as your configuration for pinCode screen will put it in reset mode...

for reference check code here: https://github.com/ecency/ecency-mobile/blob/a93b36b1d1705e4b58211a33319d78978461a2ea/src/screens/assetDetails/screen/assetDetailsScreen.tsx#L147

2023-05-30 12:26 UTC, noumantahir reviewed
Seems good from working perspective, @feruzm as for flow of things, since I was not directly part of discussion, perhaps you should review that part... if all good, can be approved and merged.

demo video:
https://github.com/ecency/ecency-mobile/assets/6298342/2e963070-6a47-44ab-9c26-34804693d0b2

2023-05-30 12:53 UTC, feruzm approved these changes
lgtm

2023-05-30 12:54 UTC, merged