feat: GU-2745 add support of repeat transfer
ecency/ecency-mobile pull request #2749
Opened 2023-09-06 14:28 UTC by gamingumar

### What does this PR?

Add repeat transfer feature

### Where should the reviewer start?

Repeat Transfer button added in Wallet Screen

### Steps to reproduce

### Issue number

https://github.com/ecency/ecency-mobile/issues/2745

### Screenshots/Video

https://github.com/ecency/ecency-mobile/assets/5675313/25be86dd-8b3d-435c-85d0-7ffdc6d67a25

2023-09-11 07:59 UTC, noumantahir requested changes
Kudos! overall great job making your way around the code, left some comments in code, functionality wise we are good.

Just need some code cleaning and we should be good...

2023-09-11 08:01 UTC, noumantahir commented
- [ ] One test we can try is to check how app would response in case of `initialAmount` from repeat activity exceeding available asset `balance`

2023-09-11 13:03 UTC, gamingumar commented on src/screens/assetDetails/children/activitiesList.tsx
> +      onActionPress('transfer_token', item);
UPDATED

2023-09-11 13:04 UTC, gamingumar commented on src/screens/transfer/screen/transferScreen.js
> +  const [amount, setAmount] = useState(transactionData ? transactionData.value?.split(' ')[0] : '');
updated

2023-09-11 13:04 UTC, gamingumar commented on src/components/basicUIElements/view/walletLineItem/walletLineItemView.tsx
> +            size={20}
updated

2023-09-11 14:24 UTC, gamingumar commented on src/screens/assetDetails/screen/assetDetailsScreen.tsx
> +          ...extraParams,
updated

2023-09-12 07:30 UTC, noumantahir commented
![Screenshot 2023-09-12 at 11 58 35 AM](https://github.com/ecency/ecency-mobile/assets/6298342/f49fe1be-2447-4af5-8e30-dabdd93f71d6)

2023-09-12 07:33 UTC, noumantahir reviewed
lgtm

2023-09-13 11:09 UTC, noumantahir approved these changes

2023-09-13 11:53 UTC, feruzm approved these changes
lgtm

2023-09-13 11:53 UTC, merged