feat: GU-2766 add flash list for performance
ecency/ecency-mobile pull request #2771
Opened 2023-10-05 08:47 UTC by gamingumar

### What does this PR?

add flash list for performance improvment

2023-10-05 10:13 UTC, noumantahir requested changes
Overall basic functionality is working fine... a couple of warnings, there is more stuttering during initial scrolls, but it adjusts after some moments...waves refresh is not working

**Initial Stutter**
first render, texts are missing, thumbnail is not well sized
![Screenshot 2023-10-05 at 2 53 55 PM](https://github.com/ecency/ecency-mobile/assets/6298342/6f73d0e8-867c-41d0-9416-3821ad206bfc)
adjusts afterwards to this
![Screenshot 2023-10-05 at 2 54 13 PM](https://github.com/ecency/ecency-mobile/assets/6298342/1862dbc3-a107-4370-81cb-1114d9e96109)


**Error**
when attempting to refresh waves
![Screenshot 2023-10-05 at 2 59 35 PM](https://github.com/ecency/ecency-mobile/assets/6298342/c8209916-94ec-4efc-a5c8-eefa4a290813)



**Warnings**
![Screenshot 2023-10-05 at 2 52 39 PM](https://github.com/ecency/ecency-mobile/assets/6298342/5b08307c-12b4-4bf2-a0e5-b25479779c8d)
![Screenshot 2023-10-05 at 2 53 31 PM](https://github.com/ecency/ecency-mobile/assets/6298342/3e3900f8-e76f-4ceb-91c4-c927e5b8c296)

2023-10-06 08:36 UTC, noumantahir commented
fixes #2766

2023-10-06 08:36 UTC, feruzm approved these changes
lgtm

2023-10-06 08:38 UTC, noumantahir approved these changes

2023-10-06 08:39 UTC, merged